version: '3.8'

services:
  llm-context-manager:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - .:/app
      - ./uploads:/app/uploads
    restart: unless-stopped
